spring:
  cloud:
    gateway:
      # discovery:
      #   locator:
      #     enabled: true
      #     lower-case-serviceid: true
      routes:
        - id: client1
          uri: lb://client-1
          predicates:
            - Weight=group1, 8
        - id: client3
          uri: lb://client-3
          predicates:
            - Weight=group1, 2

        

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 8080

gw:
  value: 20