spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-serviceid: true
      routes:
        - id: client1_v1
          uri: lb://client-1-v1
          predicates:
            - Path=/service/client-1/**
            - Weight=group1, 3
          filters:
            - RewritePath=/service/client-1/(?<segment>.*), /$\{segment}
        - id: client1_v2
          uri: lb://client-1-v2
          predicates:
            - Path=/service/client-1/**
            - Weight=group1, 7
          filters:
            - RewritePath=/service/client-1/(?<segment>.*), /$\{segment}
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
  main:
    allow-bean-definition-overriding: true

        

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

server:
  port: 8080

authentication:
  path: http://localhost:9000/authentication

gw:
  value: gw-1

client-1:
  new-version-weight: 30

client-3:
  new-version-weight: 30
